openapi: 3.0.1
info:
  title: costs-dashboard
  description: Cortex descriptor created automatically by eng-devprod
  x-cortex-tag: costs-dashboard
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: dominodatalab/costs-dashboard
  x-cortex-owners:
  - name: eng-idsm
    type: group
    provider: OKTA
    description: Updated by eng-devprod
